# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 09:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Que', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '选择题-选项管理', 'verbose_name_plural': '选择题-选项管理'},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={'verbose_name': '问卷-选择题管理', 'verbose_name_plural': '问卷-选择题管理'},
        ),
        migrations.AlterModelOptions(
            name='nonchoicequestion',
            options={'verbose_name': '无选项题管理', 'verbose_name_plural': '无选项题管理'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-created_at'], 'verbose_name': '问卷管理', 'verbose_name_plural': '问卷管理'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='descripiton',
            field=models.CharField(max_length=50, verbose_name='选项内容'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='第几个选项'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Que.ChoiceQuestion', verbose_name='问题题目'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='选项顺序'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='required',
            field=models.BooleanField(default=True, help_text='这个问题是否必须回答', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='选项顺序'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='required',
            field=models.BooleanField(default=True, help_text='这个问题是否必须回答', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='participants',
            field=models.ManyToManyField(related_name='Que_participants', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Que_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
