# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Que', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True, verbose_name='企业名称')),
                ('answer_post', models.CharField(max_length=50, verbose_name='被调查者职务或职称')),
                ('person_incharge_name', models.CharField(max_length=50, verbose_name='负责人姓名')),
                ('user_sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('user_age', models.SmallIntegerField(choices=[(0, '30岁以下'), (1, '31—40岁'), (2, '41—50岁'), (3, '51岁以上')], default=1, verbose_name='年龄')),
                ('user_edu', models.SmallIntegerField(choices=[(0, '初中'), (1, '高中（中专）'), (2, '大专'), (3, '本科'), (4, '本科以上')], default=2, verbose_name='文化程度')),
                ('user_phone', models.CharField(max_length=11, verbose_name='手机')),
                ('user_fax', models.CharField(blank=True, max_length=11, verbose_name='传真')),
                ('user_address', models.CharField(max_length=200, verbose_name='通讯地址')),
                ('establishment_time', models.DateField(verbose_name='企业成立时间')),
                ('company_url', models.URLField(blank=True, max_length=500, verbose_name='企业网址')),
                ('company_email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户信息管理',
                'verbose_name_plural': '用户信息管理',
                'ordering': ['-company_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'order_in_list'], 'verbose_name': '选择题-选项管理', 'verbose_name_plural': '选择题-选项管理'},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={'ordering': ['order_in_list'], 'verbose_name': '问卷-选择题管理', 'verbose_name_plural': '问卷-选择题管理'},
        ),
        migrations.AlterModelOptions(
            name='nonchoicequestion',
            options={'verbose_name': '无选项题管理', 'verbose_name_plural': '无选项题管理'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-created_at'], 'verbose_name': '问卷管理', 'verbose_name_plural': '问卷管理'},
        ),
        migrations.AddField(
            model_name='choice',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices_que', to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='is_first_title',
            field=models.BooleanField(default=False, verbose_name='是否为一级标题'),
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='is_second_title',
            field=models.BooleanField(default=False, verbose_name='是否为二级标题'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='question_name',
            field=models.CharField(max_length=200, null=True, verbose_name='问卷名称'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_description',
            field=models.TextField(blank=True, verbose_name='问卷说明'),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Que.AnswerUser'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='descripiton',
            field=models.CharField(max_length=50, verbose_name='选项内容'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='第几个选项'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='Que.ChoiceQuestion', verbose_name='问题题目'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='选项顺序'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='required',
            field=models.BooleanField(default=True, help_text='这个问题是否必须回答', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='order_in_list',
            field=models.IntegerField(default=1, verbose_name='选项顺序'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
        migrations.AlterField(
            model_name='nonchoicequestion',
            name='required',
            field=models.BooleanField(default=True, help_text='这个问题是否必须回答', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='participants',
            field=models.ManyToManyField(related_name='Que_participants', to='Que.AnswerUser', verbose_name='参与者'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Que_user', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
