# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-31 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Que', '0003_questionnaire_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices_que', to='Que.Questionnaire', verbose_name='问卷名称'),
        ),
    ]
